package TasteProfile;

import Implementations.SongProfileImpl;

/**
* TasteProfile/SongProfileDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* Tuesday, 25 September 2018 14:32:55 o'clock CEST
*/

public class SongProfileDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new SongProfileImpl ());
  }
}
