package TasteProfile;


/**
* TasteProfile/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* Tuesday, 25 September 2018 14:32:55 o'clock CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users*/
  int getTimesPlayed (String song_id);

  /* Returns how many times a given song was played by a given user*/
  int getTimesPlayedByUser (String user_id, String song_id);

  /*Returns top three users by song id*/
  TasteProfile.TopThree getTopThreeUsersBySong (String song_id);

  /*Returns favorite song by user id*/
  TasteProfile.Song getFavouriteSongByUser (String user_id);
  TasteProfile.UserProfile getUserProfile (String user_id);
} // interface ProfilerOperations
