package TasteProfile;


/**
* TasteProfile/Profiler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./tasteprofile.idl
* Tuesday, 25 September 2018 14:32:55 o'clock CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface Profiler extends ProfilerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Profiler
