package Implementations;

import TasteProfile.Song;
import TasteProfile.UserProfile;

/**
 * The implementation of the UserProfile that was autogenerated by the IDL
 *
 */
@SuppressWarnings("serial")
public class UserProfileImpl extends UserProfile implements Comparable<UserProfileImpl> {
	public UserProfileImpl() {
		this.id = "";
		this.total_play_count = 0;
		this.songs = new Song[0];
	}
	/**
	 * @param id The Id of the user
	 * @param playCount The number of played songs  
	 * @param songs List of songs that have been played by the user
	 */
	public void Init(String id,int playCount,Song[] songs) {
		this.id = id;
		this.total_play_count = playCount;
		this.songs = songs; 
	}
	/* (non-Javadoc)
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	@Override
	public int compareTo(UserProfileImpl e2) {
		if(this.total_play_count > e2.total_play_count) {
			return 1;
		}
		else if(this.total_play_count < e2.total_play_count) {
			return -1;
		}
		return 0;
	}

}
